boxList = [
  {
    'Name': '6x4x4',
    'Length': 6,
    'Width': 4,
    'Height': 4,
    'Double': false,
    'Flat': false,
    'Cost': 2.0
  }, {
    'Name': '9x7x5',
    'Length': 9,
    'Width': 7,
    'Height': 5,
    'Double': false,
    'Flat': false,
    'Cost': 2.5
  }, {
    'Name': '12x10x6',
    'Length': 12,
    'Width': 10,
    'Height': 6,
    'Double': false,
    'Flat': false,
    'Cost': 3.0
  }, {
    'Name': '12x12x6',
    'Length': 12,
    'Width': 12,
    'Height': 6,
    'Double': false,
    'Flat': false,
    'Cost': 4.25
  }, {
    'Name': '14x12x8',
    'Length': 14,
    'Width': 12,
    'Height': 8,
    'Double': false,
    'Flat': false,
    'Cost': 4.25
  }, {
    'Name': '15x12x10',
    'Length': 15,
    'Width': 12,
    'Height': 10,
    'Double': false,
    'Flat': false,
    'Cost': 5.0
  }, {
    'Name': '16x14x10',
    'Length': 16,
    'Width': 14,
    'Height': 10,
    'Double': false,
    'Flat': false,
    'Cost': 5.25
  }, {
    'Name': '16x16x4',
    'Length': 16,
    'Width': 16,
    'Height': 4,
    'Double': false,
    'Flat': false,
    'Cost': 5.0
  }, {
    'Name': '17x11x8',
    'Length': 17,
    'Width': 11,
    'Height': 8,
    'Double': false,
    'Flat': false,
    'Cost': 5.0
  }, {
    'Name': '18x12x6',
    'Length': 18,
    'Width': 12,
    'Height': 6,
    'Double': false,
    'Flat': false,
    'Cost': 5.25
  }, {
    'Name': '18x14x12',
    'Length': 18,
    'Width': 14,
    'Height': 12,
    'Double': false,
    'Flat': false,
    'Cost': 5.5
  }, {
    'Name': '20x12x12',
    'Length': 20,
    'Width': 12,
    'Height': 12,
    'Double': false,
    'Flat': false,
    'Cost': 7.0
  }, {
    'Name': '20x20x12',
    'Length': 20,
    'Width': 20,
    'Height': 12,
    'Double': false,
    'Flat': false,
    'Cost': 8.0
  }, {
    'Name': '20x16x16',
    'Length': 20,
    'Width': 16,
    'Height': 16,
    'Double': false,
    'Flat': false,
    'Cost': 7.25
  }, {
    'Name': '23x13x3',
    'Length': 23,
    'Width': 13,
    'Height': 3,
    'Double': false,
    'Flat': false,
    'Cost': 5.5
  }, {
    'Name': '24x18x18',
    'Length': 24,
    'Width': 18,
    'Height': 18,
    'Double': false,
    'Flat': false,
    'Cost': 8.5
  }, {
    'Name': '24x24x16',
    'Length': 24,
    'Width': 24,
    'Height': 16,
    'Double': false,
    'Flat': false,
    'Cost': 11.0
  }, {
    'Name': '26x20x6',
    'Length': 26,
    'Width': 20,
    'Height': 6,
    'Double': false,
    'Flat': false,
    'Cost': 7.0
  }, {
    'Name': '27x15x9',
    'Length': 27,
    'Width': 15,
    'Height': 9,
    'Double': false,
    'Flat': false,
    'Cost': 7.0
  }, {
    'Name': '28x20x20',
    'Length': 28,
    'Width': 20,
    'Height': 20,
    'Double': false,
    'Flat': false,
    'Cost': 13.0
  }, {
    'Name': '36x24x10',
    'Length': 36,
    'Width': 24,
    'Height': 10,
    'Double': false,
    'Flat': false,
    'Cost': 13.0
  }, {
    'Name': '12x12x40',
    'Length': 12,
    'Width': 12,
    'Height': 40,
    'Double': false,
    'Flat': false,
    'Cost': 11.0
  }, {
    'Name': '6x6x48',
    'Length': 6,
    'Width': 6,
    'Height': 48,
    'Double': false,
    'Flat': false,
    'Cost': 9.5
  }, {
    'Name': '15x15x48',
    'Length': 15,
    'Width': 15,
    'Height': 48,
    'Double': false,
    'Flat': false,
    'Cost': 13.0
  }, {
    'Name': '4x8x52',
    'Length': 4,
    'Width': 8,
    'Height': 52,
    'Double': false,
    'Flat': false,
    'Cost': 11.0
  }, {
    'Name': '6x10x102',
    'Length': 6,
    'Width': 10,
    'Height': 102,
    'Double': false,
    'Flat': false,
    'Cost': 20.0
  }, {
    'Name': '6x6x6',
    'Length': 6,
    'Width': 6,
    'Height': 6,
    'Double': false,
    'Flat': false,
    'Cost': 2.5
  }, {
    'Name': '8x8x8',
    'Length': 8,
    'Width': 8,
    'Height': 8,
    'Double': false,
    'Flat': false,
    'Cost': 3.5
  }, {
    'Name': '10x10x10',
    'Length': 10,
    'Width': 10,
    'Height': 10,
    'Double': false,
    'Flat': false,
    'Cost': 4.5
  }, {
    'Name': '12x12x12',
    'Length': 12,
    'Width': 12,
    'Height': 12,
    'Double': false,
    'Flat': false,
    'Cost': 5.5
  }, {
    'Name': '14x14x14',
    'Length': 14,
    'Width': 14,
    'Height': 14,
    'Double': false,
    'Flat': false,
    'Cost': 6.5
  }, {
    'Name': '16x16x16',
    'Length': 16,
    'Width': 16,
    'Height': 16,
    'Double': false,
    'Flat': false,
    'Cost': 8.0
  }, {
    'Name': '18x18x18',
    'Length': 18,
    'Width': 18,
    'Height': 18,
    'Double': false,
    'Flat': false,
    'Cost': 8.0
  }, {
    'Name': '20x20x20',
    'Length': 20,
    'Width': 20,
    'Height': 20,
    'Double': false,
    'Flat': false,
    'Cost': 12.0
  }, {
    'Name': '20x16x16',
    'Length': 20,
    'Width': 16,
    'Height': 16,
    'Double': true,
    'Flat': false,
    'Cost': 12.0
  }, {
    'Name': '24x18x18',
    'Length': 24,
    'Width': 18,
    'Height': 18,
    'Double': true,
    'Flat': false,
    'Cost': 15.0
  }, {
    'Name': '18x18x28',
    'Length': 18,
    'Width': 18,
    'Height': 28,
    'Double': true,
    'Flat': false,
    'Cost': 12.0
  }, {
    'Name': '26x20x20',
    'Length': 26,
    'Width': 20,
    'Height': 20,
    'Double': true,
    'Flat': false,
    'Cost': 12.0
  }, {
    'Name': '30x20x20',
    'Length': 30,
    'Width': 20,
    'Height': 20,
    'Double': true,
    'Flat': false,
    'Cost': 20.0
  }, {
    'Name': '32x24x24',
    'Length': 32,
    'Width': 24,
    'Height': 24,
    'Double': true,
    'Flat': false,
    'Cost': 22.0
  }, {
    'Name': '36x22x22',
    'Length': 36,
    'Width': 22,
    'Height': 22,
    'Double': true,
    'Flat': false,
    'Cost': 25.0
  }, {
    'Name': '10x20x50',
    'Length': 10,
    'Width': 20,
    'Height': 50,
    'Double': true,
    'Flat': false,
    'Cost': 18.0
  }, {
    'Name': '42x29x26',
    'Length': 42,
    'Width': 29,
    'Height': 26,
    'Double': true,
    'Flat': false,
    'Cost': 30.0
  }, {
    'Name': '18x21x46',
    'Length': 18,
    'Width': 21,
    'Height': 46,
    'Double': true,
    'Flat': false,
    'Cost': 18.0
  }, {
    'Name': '21x24x47',
    'Length': 21,
    'Width': 24,
    'Height': 47,
    'Double': true,
    'Flat': false,
    'Cost': 22.0
  }, {
    'Name': '24x6x18',
    'Length': 24,
    'Width': 6,
    'Height': 18,
    'Double': false,
    'Flat': true,
    'Cost': 11.0
  }, {
    'Name': '27x23x4',
    'Length': 27,
    'Width': 23,
    'Height': 4,
    'Double': false,
    'Flat': true,
    'Cost': 11.0
  }, {
    'Name': '30x6x24',
    'Length': 30,
    'Width': 6,
    'Height': 24,
    'Double': false,
    'Flat': true,
    'Cost': 12.0
  }, {
    'Name': '36x6x29',
    'Length': 36,
    'Width': 6,
    'Height': 29,
    'Double': false,
    'Flat': true,
    'Cost': 15.0
  }, {
    'Name': '36x8x30',
    'Length': 36,
    'Width': 8,
    'Height': 30,
    'Double': false,
    'Flat': true,
    'Cost': 16.5
  }, {
    'Name': '35x6x44',
    'Length': 35,
    'Width': 6,
    'Height': 44,
    'Double': false,
    'Flat': true,
    'Cost': 18.0
  }, {
    'Name': '45x8x32',
    'Length': 45,
    'Width': 8,
    'Height': 32,
    'Double': false,
    'Flat': true,
    'Cost': 20.0
  }, {
    'Name': '53x7x30',
    'Length': 53,
    'Width': 7,
    'Height': 30,
    'Double': false,
    'Flat': true,
    'Cost': 25.0
  }, {
    'Name': '56x10x32',
    'Length': 56,
    'Width': 10,
    'Height': 32,
    'Double': false,
    'Flat': true,
    'Cost': 40.0
  }, {
    'Name': '64x8x40',
    'Length': 64,
    'Width': 8,
    'Height': 40,
    'Double': false,
    'Flat': true,
    'Cost': 95.0
  }, {
    'Name': '22x22x22',
    'Length': 22,
    'Width': 22,
    'Height': 22,
    'Double': true,
    'Flat': false,
    'Cost': 18.0
  }, {
    'Name': '24x24x24',
    'Length': 24,
    'Width': 24,
    'Height': 24,
    'Double': false,
    'Flat': false,
    'Cost': 20.0
  }, {
    'Name': '25x25x25',
    'Length': 25,
    'Width': 25,
    'Height': 25,
    'Double': true,
    'Flat': false,
    'Cost': 22.0
  }, {
    'Name': '28x28x28',
    'Length': 28,
    'Width': 28,
    'Height': 28,
    'Double': true,
    'Flat': false,
    'Cost': 32.0
  }, {
    'Name': '30x30x30',
    'Length': 30,
    'Width': 30,
    'Height': 30,
    'Double': true,
    'Flat': false,
    'Cost': 60.0
  }, {
    'Name': '36x36x36',
    'Length': 36,
    'Width': 36,
    'Height': 36,
    'Double': true,
    'Flat': false,
    'Cost': 75.0
  }];
// function to put the boxes away into the lists
function Place_Box(characteristic, detail, price) {
  let itemID = document.getElementById(characteristic);
  itemID.insertAdjacentHTML(
    "beforeend",
    "<tr class = 'insertedContent'><th>" + detail + "</th><th>$" + price + "</th></tr>"
  );
}
for (box in boxList) {
  let BOX = boxList[box];
  let cost = parseFloat(BOX.Cost).toFixed(2);
  if (BOX.Double == true) {
    Place_Box("double", BOX.Name, cost);
  } else if (BOX.Flat == true) {
    Place_Box("flat", BOX.Name, cost);
  } else if (BOX.Length == BOX.Height && BOX.Width == BOX.Length) {
    Place_Box("cube", BOX.Name, cost);
  } else {
    Place_Box("single", BOX.Name, cost);
  }
}